### ISSUE TITLE
木有教程？

### ISSUE THREAD

**Issue by iPixelOldC** [hanbang-wang/SAKS-SDK-GO#1]
话说除了test里面的点点实例，就没有教程了？QAQ，有时间能不能写个教程啊，谢谢啊

**Comment by superfashi** [comment]
这个用法和Python的一样，去看看Python的就知道了。

**Comment by iPixelOldC** [comment]
没事没事，我刚刚开始时想复杂了，后来跑去看了下源码，大致都会了。。。接下来就是实际实验了。。。

**Comment by iPixelOldC** [comment]
没事没事，我刚刚开始时想复杂了，后来跑去看了下源码，大致都会了。。。接下来就是实际实验了。。。
